version: '3.1'

services:
  db:
    image: mysql
    container_name: mod06-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:3306' 